# Generated by Django 2.2.1 on 2020-01-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20200108_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('code', models.CharField(max_length=4)),
                ('student', models.ManyToManyField(related_name='student', to='demoapp.Student')),
            ],
        ),
    ]
