# Generated by Django 2.2.1 on 2020-01-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.CharField(max_length=123)),
            ],
        ),
    ]
