# Generated by Django 2.2.1 on 2020-01-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_auto_20200110_0739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New1',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='test.png', upload_to='student_pics'),
        ),
    ]
